package runner_test

import (
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/rognerud/dbt-ditto/internal/config"
	"github.com/rognerud/dbt-ditto/internal/runner"
)

// TestParityWithDbtOsmosis is the parity proof, run without Python.
//
// testdata/golden/osmosis holds the schema YAML that the real dbt-osmosis wrote
// for the platform fixture; it is regenerated by scripts/parity.sh, which runs
// dbt-osmosis for real and diffs it against dbt-ditto. This test replays the
// dbt-ditto half against the recorded result, so a change in behaviour that
// breaks parity fails the ordinary test run rather than waiting for someone to
// have dbt installed.
func TestParityWithDbtOsmosis(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping the dbt-osmosis parity proof in short mode")
	}
	work := copyFixture(t)

	cfg := fixtureConfig(work)
	// These three must match scripts/parity.sh exactly, since that is what
	// produced the golden files. See the comment there for why each is needed.
	osmosisComments := config.CommentsOsmosis
	cfg.Output.Comments = &osmosisComments
	noWarehouseComments := config.WarehouseCommentsNever
	cfg.Columns.Comments = &noWarehouseComments
	off := false
	cfg.Inheritance.Progenitor = &off

	if _, err := runner.Run(cfg, runner.Options{Organize: true}); err != nil {
		t.Fatalf("run: %v", err)
	}

	golden := repoPath(t, "testdata", "golden", "osmosis")
	assertTreeEqual(t, golden, filepath.Join(work, "platform"))
}

// TestCrossProjectGolden covers what dbt-osmosis cannot do at all: inheriting
// across two separately parsed projects. dbt-osmosis and dbt-loom cannot run
// together (see testdata/golden/osmosis-analytics-failure.log), so the reference
// here is dbt-ditto' own recorded output.
func TestCrossProjectGolden(t *testing.T) {
	work := copyFixture(t)

	if _, err := runner.Run(fixtureConfig(work), runner.Options{Organize: true}); err != nil {
		t.Fatalf("run: %v", err)
	}

	golden := repoPath(t, "testdata", "golden", "dbt-ditto", "analytics")
	assertTreeEqual(t, golden, filepath.Join(work, "analytics"))
}

// TestDerivedInheritanceEndToEnd covers the one thing dbt-ditto deliberately
// does that dbt-osmosis does not: following a column's documentation through a
// rename, in both directions, on the real DuckDB fixture.
func TestDerivedInheritanceEndToEnd(t *testing.T) {
	work := copyFixture(t)

	cfg := fixtureConfig(work)
	on := true
	cfg.Inheritance.Derived.Enabled = &on

	if _, err := runner.Run(cfg, runner.Options{Organize: true}); err != nil {
		t.Fatalf("run: %v", err)
	}

	cases := []struct {
		file   string
		column string
		want   string
		why    string
	}{
		{
			"models/marts/_fct_customer_totals.yml", "total_amount_cents",
			"Order gross value in minor currency units.",
			"sum(amount_cents) keeps the meaning of amount_cents",
		},
		{
			"models/marts/_fct_customer_totals.yml", "max_order_date",
			"Calendar date the order was placed, in UTC.",
			"max(order_date) keeps the meaning of order_date",
		},
		{
			"models/marts/_dim_customer_profile.yml", "profile.first_name",
			"Customer given name, as typed by the customer.",
			"packing a column into a struct carries its documentation in",
		},
		{
			"models/marts/_dim_customer_flat.yml", "first_name",
			"Customer given name, as typed by the customer.",
			"and unpacking it again carries the documentation back out",
		},
	}

	files := snapshotTree(t, filepath.Join(work, "platform"))
	for _, c := range cases {
		content, ok := files[c.file]
		if !ok {
			t.Errorf("%s: not written", c.file)
			continue
		}
		if !strings.Contains(content, "- name: "+c.column+"\n") {
			t.Errorf("%s: no entry for %s (%s):\n%s", c.file, c.column, c.why, content)
			continue
		}
		if !strings.Contains(content, c.want) {
			t.Errorf("%s: %s did not inherit %q (%s):\n%s",
				c.file, c.column, c.want, c.why, content)
		}
	}
}

// The same fixture with derived matching left alone must produce none of that,
// which is what keeps the dbt-osmosis parity claim honest.
func TestDerivedInheritanceIsOffByDefault(t *testing.T) {
	work := copyFixture(t)
	if _, err := runner.Run(fixtureConfig(work), runner.Options{Organize: true}); err != nil {
		t.Fatalf("run: %v", err)
	}

	files := snapshotTree(t, filepath.Join(work, "platform"))
	totals := files["models/marts/_fct_customer_totals.yml"]
	if strings.Contains(totals, "Order gross value") {
		t.Errorf("an aggregated column inherited by default:\n%s", totals)
	}
	profile := files["models/marts/_dim_customer_profile.yml"]
	if !strings.Contains(profile, "- name: profile.first_name\n") {
		t.Errorf("struct fields should still be expanded by default, as dbt-osmosis does:\n%s", profile)
	}
	if strings.Contains(profile, "Customer given name") {
		t.Errorf("a struct field inherited by default:\n%s", profile)
	}
}

// TestSourceDocumentationEndToEnd covers the case ordinary inheritance cannot
// reach: a raw source table, which is a root of the DAG and so has nothing
// upstream to inherit from. The fixture's `billing` source documents none of
// its columns, and both routes to documenting it are exercised at once.
func TestSourceDocumentationEndToEnd(t *testing.T) {
	work := copyFixture(t)

	cfg := fixtureConfig(work)
	on := true
	cfg.Inheritance.Backfill.Enabled = &on

	if _, err := runner.Run(cfg, runner.Options{Organize: true}); err != nil {
		t.Fatalf("run: %v", err)
	}

	sources := snapshotTree(t, filepath.Join(work, "platform"))["models/staging/_sources.yml"]
	if sources == "" {
		t.Fatal("the sources file was not written")
	}

	cases := []struct {
		column string
		want   string
		why    string
	}{
		{
			"invoice_id", "Surrogate key for an invoice, assigned by the billing system.",
			"backfilled from the staging model that reads the source",
		},
		{
			"invoice_total_cents", "Invoice total in minor currency units, including tax.",
			"likewise",
		},
		{
			"issued_on", "Calendar date the invoice was issued, in UTC.",
			"likewise",
		},
		{
			"order_id", "Order this invoice bills for, as recorded by the billing system.",
			"nothing in dbt documents it; this is the warehouse's own COMMENT",
		},
	}
	for _, c := range cases {
		if !strings.Contains(sources, c.want) {
			t.Errorf("%s did not get its description (%s):\n%s", c.column, c.why, sources)
		}
	}
}

// TestRunIsIdempotent checks that a second run over an already-documented
// project changes nothing, which is what makes `--check` usable in CI.
func TestRunIsIdempotent(t *testing.T) {
	work := copyFixture(t)

	first, err := runner.Run(fixtureConfig(work), runner.Options{Organize: true})
	if err != nil {
		t.Fatalf("first run: %v", err)
	}
	if len(first.FilesWritten) == 0 {
		t.Fatal("first run wrote nothing, so the fixture proves nothing")
	}

	second, err := runner.Run(fixtureConfig(work), runner.Options{Organize: true})
	if err != nil {
		t.Fatalf("second run: %v", err)
	}
	if len(second.FilesWritten) != 0 || len(second.FilesDeleted) != 0 {
		t.Errorf("second run was not a no-op: wrote %v, deleted %v",
			second.FilesWritten, second.FilesDeleted)
	}
}

// TestCheckModeReportsWithoutWriting makes sure --check neither writes nor
// hides pending changes.
func TestCheckModeReportsWithoutWriting(t *testing.T) {
	work := copyFixture(t)

	before := snapshotTree(t, filepath.Join(work, "platform"))
	rep, err := runner.Run(fixtureConfig(work), runner.Options{
		DryRun: true, Check: true, Organize: true,
	})
	if err != nil {
		t.Fatalf("run: %v", err)
	}
	if len(rep.FilesWritten) == 0 {
		t.Error("check mode reported no pending writes on an out-of-date fixture")
	}
	after := snapshotTree(t, filepath.Join(work, "platform"))
	if len(before) != len(after) {
		t.Fatalf("check mode changed the file set: %d files before, %d after", len(before), len(after))
	}
	for path, content := range before {
		if after[path] != content {
			t.Errorf("check mode modified %s", path)
		}
	}
}

// TestSelectLimitsScope checks that --select really does confine the run.
func TestSelectLimitsScope(t *testing.T) {
	work := copyFixture(t)

	rep, err := runner.Run(fixtureConfig(work), runner.Options{
		Organize: true,
		Select:   []string{"stg_customers"},
	})
	if err != nil {
		t.Fatalf("run: %v", err)
	}
	if rep.NodesScanned != 1 {
		t.Errorf("scanned %d nodes, want 1", rep.NodesScanned)
	}
	for _, f := range rep.FilesWritten {
		if !strings.Contains(f, "stg_customers") {
			t.Errorf("selecting stg_customers also wrote %s", f)
		}
	}
}

// --- helpers ---------------------------------------------------------------

// fixtureConfig mirrors testdata/dbt_ditto.yml, pointed at a scratch copy.
func fixtureConfig(root string) *config.Config {
	return &config.Config{
		Dir: root,
		Projects: []config.ProjectRef{
			{Name: "platform", Path: filepath.Join(root, "platform")},
			{Name: "analytics", Path: filepath.Join(root, "analytics")},
		},
	}
}

// repoPath resolves a path relative to the repository root.
func repoPath(t *testing.T, parts ...string) string {
	t.Helper()
	root, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatalf("locate repo root: %v", err)
	}
	return filepath.Join(append([]string{root}, parts...)...)
}

// copyFixture puts a writable copy of testdata/projects in a temp directory.
func copyFixture(t *testing.T) string {
	t.Helper()
	src := repoPath(t, "testdata", "projects")
	dst := t.TempDir()
	if err := copyTree(src, dst); err != nil {
		t.Fatalf("copy fixture: %v", err)
	}
	return dst
}

func copyTree(src, dst string) error {
	return filepath.Walk(src, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(src, path)
		if err != nil {
			return err
		}
		target := filepath.Join(dst, rel)
		if info.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		if !info.Mode().IsRegular() {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		return os.WriteFile(target, data, info.Mode().Perm())
	})
}

// snapshotTree reads every schema YAML under root, keyed by relative path.
func snapshotTree(t *testing.T, root string) map[string]string {
	t.Helper()
	out := map[string]string{}
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			if name := info.Name(); name == "target" || name == "logs" {
				return filepath.SkipDir
			}
			return nil
		}
		if !isSchemaYAML(path) {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		out[filepath.ToSlash(rel)] = string(data)
		return nil
	})
	if err != nil {
		t.Fatalf("walk %s: %v", root, err)
	}
	return out
}

// isSchemaYAML excludes the YAML that is configuration rather than docs.
func isSchemaYAML(path string) bool {
	base := filepath.Base(path)
	if base == "dbt_project.yml" || base == "profiles.yml" || base == ".user.yml" ||
		base == "dbt_loom.config.yml" || base == "dbt_ditto.yml" {
		return false
	}
	return strings.HasSuffix(base, ".yml") || strings.HasSuffix(base, ".yaml")
}

// assertTreeEqual compares two trees of schema YAML, contents and file set.
func assertTreeEqual(t *testing.T, want, got string) {
	t.Helper()
	wantFiles := snapshotTree(t, want)
	gotFiles := snapshotTree(t, got)

	for _, name := range sortedKeys(wantFiles) {
		g, ok := gotFiles[name]
		if !ok {
			t.Errorf("%s: missing from the output", name)
			continue
		}
		if g != wantFiles[name] {
			t.Errorf("%s differs:\n--- want ---\n%s\n--- got ---\n%s", name, wantFiles[name], g)
		}
	}
	for _, name := range sortedKeys(gotFiles) {
		if _, ok := wantFiles[name]; !ok {
			t.Errorf("%s: unexpected file in the output", name)
		}
	}
}

func sortedKeys(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
