package runner_test

import (
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/rognerud/dbt-ditto/internal/config"
	"github.com/rognerud/dbt-ditto/internal/runner"
)

// TestParityWithDbtOsmosis is the parity proof, run without Python:
// testdata/golden/osmosis holds what the real dbt-osmosis wrote for the platform
// fixture, regenerated by scripts/parity.sh.
func TestParityWithDbtOsmosis(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping the dbt-osmosis parity proof in short mode")
	}
	// These three must match scripts/parity.sh, which produced the golden files.
	work, _ := runFixture(t, func(c *config.Config) {
		c.Output.Comments = ptrTo(config.CommentsOsmosis)
		c.Columns.Comments = ptrTo(config.WarehouseCommentsNever)
		c.Inheritance.Progenitor = ptrTo(false)
	})
	assertTreeEqual(t, repoPath(t, "testdata", "golden", "osmosis"),
		filepath.Join(work, "platform"))
}

// TestCrossProjectGolden covers what dbt-osmosis cannot do at all: inheriting across
// two separately parsed projects.
func TestCrossProjectGolden(t *testing.T) {
	work, _ := runFixture(t, nil)
	assertTreeEqual(t, repoPath(t, "testdata", "golden", "dbt-ditto", "analytics"),
		filepath.Join(work, "analytics"))
}

// TestDerivedInheritanceEndToEnd covers the one thing dbt-ditto deliberately
// does that dbt-osmosis does not: following documentation through a rename, in
// both directions, on the real DuckDB fixture.
func TestDerivedInheritanceEndToEnd(t *testing.T) {
	work, _ := runFixture(t, func(c *config.Config) {
		c.Inheritance.Derived.Enabled = ptrTo(true)
	})

	cases := []struct{ file, column, want, why string }{
		{"models/marts/_fct_customer_totals.yml", "total_amount_cents",
			"Order gross value in minor currency units.",
			"sum(amount_cents) keeps the meaning of amount_cents"},
		{"models/marts/_fct_customer_totals.yml", "max_order_date",
			"Calendar date the order was placed, in UTC.",
			"max(order_date) keeps the meaning of order_date"},
		{"models/marts/_dim_customer_profile.yml", "profile.first_name",
			"Customer given name, as typed by the customer.",
			"packing a column into a struct carries its documentation in"},
		{"models/marts/_dim_customer_flat.yml", "first_name",
			"Customer given name, as typed by the customer.",
			"and unpacking it again carries the documentation back out"},
	}

	files := snapshotTree(t, filepath.Join(work, "platform"))
	for _, c := range cases {
		content, ok := files[c.file]
		switch {
		case !ok:
			t.Errorf("%s: not written", c.file)
		case !strings.Contains(content, "- name: "+c.column+"\n"):
			t.Errorf("%s: no entry for %s (%s):\n%s", c.file, c.column, c.why, content)
		case !strings.Contains(content, c.want):
			t.Errorf("%s: %s did not inherit %q (%s):\n%s",
				c.file, c.column, c.want, c.why, content)
		}
	}
}

// The same fixture with derived matching left alone must produce none of that.
func TestDerivedInheritanceIsOffByDefault(t *testing.T) {
	work, _ := runFixture(t, nil)
	files := snapshotTree(t, filepath.Join(work, "platform"))

	totals := files["models/marts/_fct_customer_totals.yml"]
	if strings.Contains(totals, "Order gross value") {
		t.Errorf("an aggregated column inherited by default:\n%s", totals)
	}
	profile := files["models/marts/_dim_customer_profile.yml"]
	if !strings.Contains(profile, "- name: profile.first_name\n") {
		t.Errorf("struct fields should still be expanded by default, as dbt-osmosis does:\n%s", profile)
	}
	if strings.Contains(profile, "Customer given name") {
		t.Errorf("a struct field inherited by default:\n%s", profile)
	}
}

// TestSourceDocumentationEndToEnd covers what ordinary inheritance cannot reach: a raw
// source, a DAG root with nothing upstream.
func TestSourceDocumentationEndToEnd(t *testing.T) {
	work, _ := runFixture(t, func(c *config.Config) {
		c.Inheritance.Backfill.Enabled = ptrTo(true)
	})

	sources := snapshotTree(t, filepath.Join(work, "platform"))["models/staging/_sources.yml"]
	if sources == "" {
		t.Fatal("the sources file was not written")
	}

	// The first three are backfilled from the staging model that reads the
	// source; nothing in dbt documents order_id, so that is the warehouse's own
	// COMMENT arriving through the catalog.
	for _, want := range []string{
		"Surrogate key for an invoice, assigned by the billing system.",
		"Invoice total in minor currency units, including tax.",
		"Calendar date the invoice was issued, in UTC.",
		"Order this invoice bills for, as recorded by the billing system.",
	} {
		if !strings.Contains(sources, want) {
			t.Errorf("the source did not get %q:\n%s", want, sources)
		}
	}
}

// TestRunIsIdempotent: a second run over a documented project changes nothing,
// which is what makes `--check` usable in CI.
func TestRunIsIdempotent(t *testing.T) {
	work, first := runFixture(t, nil)
	if len(first.FilesWritten) == 0 {
		t.Fatal("first run wrote nothing, so the fixture proves nothing")
	}

	second, err := runner.Run(fixtureConfig(work), runner.Options{Organize: true})
	if err != nil {
		t.Fatalf("second run: %v", err)
	}
	if len(second.FilesWritten) != 0 || len(second.FilesDeleted) != 0 {
		t.Errorf("second run was not a no-op: wrote %v, deleted %v",
			second.FilesWritten, second.FilesDeleted)
	}
}

// TestCheckModeReportsWithoutWriting: --check neither writes nor hides changes.
func TestCheckModeReportsWithoutWriting(t *testing.T) {
	work := copyFixture(t)
	before := snapshotTree(t, filepath.Join(work, "platform"))

	rep, err := runner.Run(fixtureConfig(work), runner.Options{
		DryRun: true, Check: true, Organize: true,
	})
	if err != nil {
		t.Fatalf("run: %v", err)
	}
	if len(rep.FilesWritten) == 0 {
		t.Error("check mode reported no pending writes on an out-of-date fixture")
	}

	after := snapshotTree(t, filepath.Join(work, "platform"))
	if len(before) != len(after) {
		t.Fatalf("check mode changed the file set: %d files before, %d after", len(before), len(after))
	}
	for path, content := range before {
		if after[path] != content {
			t.Errorf("check mode modified %s", path)
		}
	}
}

// TestSelectLimitsScope checks that --select really does confine the run.
func TestSelectLimitsScope(t *testing.T) {
	work := copyFixture(t)
	rep, err := runner.Run(fixtureConfig(work), runner.Options{
		Organize: true,
		Select:   []string{"stg_customers"},
	})
	if err != nil {
		t.Fatalf("run: %v", err)
	}
	if rep.NodesScanned != 1 {
		t.Errorf("scanned %d nodes, want 1", rep.NodesScanned)
	}
	for _, f := range rep.FilesWritten {
		if !strings.Contains(f, "stg_customers") {
			t.Errorf("selecting stg_customers also wrote %s", f)
		}
	}
}

// --- helpers ---------------------------------------------------------------

// runFixture copies testdata/projects, applies tweak to the config it mirrors,
// and runs over the copy. Nearly every end-to-end test differs only in tweak.
func runFixture(t *testing.T, tweak func(*config.Config)) (string, *runner.Report) {
	t.Helper()
	work := copyFixture(t)
	cfg := fixtureConfig(work)
	if tweak != nil {
		tweak(cfg)
	}
	rep, err := runner.Run(cfg, runner.Options{Organize: true})
	if err != nil {
		t.Fatalf("run: %v", err)
	}
	return work, rep
}

// fixtureConfig mirrors testdata/dbt_ditto.yml, pointed at a scratch copy.
func fixtureConfig(root string) *config.Config {
	return &config.Config{
		Dir: root,
		Projects: []config.ProjectRef{
			{Name: "platform", Path: filepath.Join(root, "platform")},
			{Name: "analytics", Path: filepath.Join(root, "analytics")},
		},
	}
}

// repoPath resolves a path relative to the repository root.
func repoPath(t *testing.T, parts ...string) string {
	t.Helper()
	root, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatalf("locate repo root: %v", err)
	}
	return filepath.Join(append([]string{root}, parts...)...)
}

// copyFixture puts a writable copy of testdata/projects in a temp directory.
func copyFixture(t *testing.T) string {
	t.Helper()
	dst := t.TempDir()
	if err := copyTree(repoPath(t, "testdata", "projects"), dst); err != nil {
		t.Fatalf("copy fixture: %v", err)
	}
	return dst
}

func copyTree(src, dst string) error {
	return filepath.Walk(src, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(src, path)
		if err != nil {
			return err
		}
		target := filepath.Join(dst, rel)
		if info.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		if !info.Mode().IsRegular() {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		return os.WriteFile(target, data, info.Mode().Perm())
	})
}

// snapshotTree reads every schema YAML under root, keyed by relative path.
func snapshotTree(t *testing.T, root string) map[string]string {
	t.Helper()
	out := map[string]string{}
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			if name := info.Name(); name == "target" || name == "logs" {
				return filepath.SkipDir
			}
			return nil
		}
		if !isSchemaYAML(path) {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		out[filepath.ToSlash(rel)] = string(data)
		return nil
	})
	if err != nil {
		t.Fatalf("walk %s: %v", root, err)
	}
	return out
}

// isSchemaYAML excludes the YAML that is configuration rather than docs.
func isSchemaYAML(path string) bool {
	switch base := filepath.Base(path); base {
	case "dbt_project.yml", "profiles.yml", ".user.yml", "dbt_loom.config.yml", "dbt_ditto.yml":
		return false
	default:
		return strings.HasSuffix(base, ".yml") || strings.HasSuffix(base, ".yaml")
	}
}

// assertTreeEqual compares two trees of schema YAML, contents and file set.
func assertTreeEqual(t *testing.T, want, got string) {
	t.Helper()
	wantFiles := snapshotTree(t, want)
	gotFiles := snapshotTree(t, got)

	for _, name := range sortedKeys(wantFiles) {
		g, ok := gotFiles[name]
		if !ok {
			t.Errorf("%s: missing from the output", name)
			continue
		}
		if g != wantFiles[name] {
			t.Errorf("%s differs:\n--- want ---\n%s\n--- got ---\n%s", name, wantFiles[name], g)
		}
	}
	for _, name := range sortedKeys(gotFiles) {
		if _, ok := wantFiles[name]; !ok {
			t.Errorf("%s: unexpected file in the output", name)
		}
	}
}

func sortedKeys(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
